builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: all_packages
    build_to: cache

targets:
  $default:
    sources:
      exclude:
        # has some faulty component declarations, might not need generation, but comment out for now cuz it breaks things
        - "test/over_react/component_declaration/transformer_helpers_test.dart"

    builders:
      # builder uses mirrors and will cause a build to fail when using build web compilers
      # vm tests require the use of mirrors
      build_web_compilers|ddc:
        generate_for:
          exclude:
            - "test/vm_tests/**"
            - "test/builder/**"
            - "lib/src/builder/**"
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - "test/vm_tests/**"
            - "test/builder/**"
            - "lib/src/builder/**"

